version: "3"

services:
  app:
    build:
      # poetry.lockファイルをコピーするためにビルドは親ディレクトリで行う
      context: ../
      dockerfile: .devcontainer/Dockerfile
    environment:
      - DISPLAY=host.docker.internal:0.0
      - COMPOSE_PROJECT_NAME=KeyAdjuster
    volumes:
      - ../..:/workspace:cached
      - ~/.aws:/root/.aws
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
    command: sleep infinity
